name: build dev project
on: 
  push:
    branches:
      - master  #event trigger
jobs:
  build:
    runs-on: ubuntu-latest #runner
    steps:
      - name: checkout code 
        run: echo "checkout code"
      - name: build
        run: npm run build