name: first action
on: 
  push:
    branches:
      - master
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: print greeting #步驟名稱
        run: echo "greeting" #執行命令(action)
      - name: print byebye #步驟名稱
        run: echo "bye bye" #執行命令(action)
  deploy: 
    runs-on: ubuntu-latest 
    needs: build
    steps:
      - name: print deploy #步驟名稱
        run: echo ${{ github }} #執行命令(action)