name: first action
on: [ workflow_dispatch ]
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: print greeting #步驟名稱
        run: echo "greeting" #執行命令(action)
      - name: print byebye #步驟名稱
        run: echo "bye bye" #執行命令(action)
      - name: create node.js env
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: install
        run: npm ci