name: first action 
on: 
  push:
    branches:
      - master

	pull_request:
		branches:
			- master
jobs:
  build: 
    runs-on: ubuntu-latest 
    steps:
      - name: print greeting 
        run: echo "greeting" 
      - name: print byebye 
        run: echo "bye bye" 